name: Docker Image for Spotify-Lab

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Spotify-Lab
              uses: actions/checkout@v1
            - name: Build and Publish Spotify-Lab Docker Image
              uses: jerray/publish-docker-action@master
              id: docker
              with:
                  username: joewood
                  password: ${{ secrets.GITHUB_TOKEN }}
                  registry: docker.pkg.github.com
                  repository: joewood/spotify-lab/main
                  tags: latest
                  cache: false
